version: "3.9"

services:

  mongo:
    image: mongo:7
    container_name: mongo-albums
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  create:
    build: ./create
    ports:
      - "8001:8001"
    environment:
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
    depends_on:
      - mongo

  read:
    build: ./read
    ports:
      - "8002:8002"
    environment:
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
    depends_on:
      - mongo

  update:
    build: ./update
    ports:
      - "8003:8003"
    environment:
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
    depends_on:
      - mongo

  delete:
    build: ./delete
    ports:
      - "8004:8004"
    environment:
      MONGO_URI: "mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017"
      MONGO_DB: ${MONGO_DB}
      MONGO_COLLECTION: ${MONGO_COLLECTION}
    depends_on:
      - mongo

volumes:
  mongo_data:
